log:
  path: /tmp/aibeing.log

ws:
  port: 8823
  ping_interval: 20  # 心跳间隔
  ping_timeout: 20   # 心跳超时

mysql:
  dsn: mysql+mysqlconnector://root:123456@localhost/aibeing

redis:
  host: 127.0.0.1
  port: 6379
  db: 0

llm:
  async: false
  embedding: /Users/huaxinrui/AIB/aibeing/interact/llm/vector/embedding # or openai
  type: msai # or openai
  jupyter_port: 10010
  msai_addr: http://msai.tal.com/openai/deployments/gpt-4/chat/completions?api-version=2023-07-01-preview
  msai_max_token: 8000

audio:
  upload_path: "/tmp/"
  save_path: /tmp/
  image_path: /tmp/



vector:
  mode: "server"
  host: "127.0.0.1"
#  host: "47.253.53.220"
  port: 8000


